### ISSUE TITLE
env-kernel doesn't work on Windows

### ISSUE THREAD

**Issue by dhirschfeld** [minrk/a2km#2]
Win10 / Anaconda3.4 Ruby 2.2.2p95 (all x64)

```
C:\Users\Dave\Code\conda\snakeviz>a2km env-kernel py27
Making kernel 'py27' for conda:py27
bash: line 2: activate: No such file or directory
error: Failed to run python -c 'import ipykernel; print(ipykernel.__version__)' in conda env: py27. Use --trace to view backtrace

C:\Users\Dave\Code\conda\snakeviz>a2km --trace env-kernel py27
Making kernel 'py27' for conda:py27
bash: line 2: activate: No such file or directory
C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/lib/a2km/env.rb:47:in `block in in_env': Failed to run python -c 'import ipykernel; print(ipykernel.__version__)' in conda env: py27 (ENVError)
        from C:/bin/ruby22-x64/lib/ruby/2.2.0/Open3.rb:199:in `popen_run'
        from C:/bin/ruby22-x64/lib/ruby/2.2.0/Open3.rb:145:in `popen2'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/lib/a2km/env.rb:40:in `in_env'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/lib/a2km/env.rb:59:in `ipykernel_version'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/lib/a2km/env.rb:81:in `make_env_kernel'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/lib/a2km/command.rb:183:in `block (2 levels) in run'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/runner.rb:68:in `run!'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/lib/a2km/command.rb:257:in `run'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/lib/a2km/command.rb:13:in `run'
        from C:/bin/ruby22-x64/lib/ruby/gems/2.2.0/gems/a2km-0.0.3/bin/a2km:5:in `<top (required)>'
        from C:/bin/ruby22-x64/bin/a2km:23:in `load'
        from C:/bin/ruby22-x64/bin/a2km:23:in `<main>'

C:\Users\Dave\Code\conda\snakeviz>python -c 'import ipykernel; print(ipykernel.__version__)'
  File "<string>", line 1
    'import
          ^
SyntaxError: EOL while scanning string literal

C:\Users\Dave\Code\conda\snakeviz>python -c "import ipykernel; print(ipykernel.__version__)"
4.0.
```

**Comment by dhirschfeld** [comment]
Changing the order of the quotes didn't help...

```
C:\Users\Dave\Code\conda\snakeviz>a2km env-kernel py27
Making kernel 'py27' for conda:py27
bash: line 2: activate: No such file or directory
error: Failed to run python -c "import ipykernel; print(ipykernel.__version__)" in conda env: py27. Use --trace to view backtrace
```

...looks like it can't see the `activate.bat` file despite it being in the path of the terminal

```
C:\Users\Dave\Code\conda\snakeviz>where activate
C:\Anaconda3\Scripts\activate.bat
```

**Comment by dhirschfeld** [comment]
...and the culprit is the [`CONDA_ACTIVATE`](https://github.com/minrk/a2km/blob/master/lib/a2km/env.rb#L23) command which on windows should be:

```
CONDA_ACTIVATE = 'activate.bat'
```

I'd submit a PR but my ruby skills are non-existant so I'm not sure how you'd switch  based on the OS.

**Comment by minrk** [comment]
I'm not sure how any of this would work on Windows. I don't have access to any Windows systems at the moment, so I'm only testing on OS X.

**Comment by minrk** [comment]
Since Windows has no `exec`, I think roughly everything about this would have to be different to work on Windows.
